//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parlis.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Parlis.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string ACCEPT_BUTTON {
            get {
                return ResourceManager.GetString("ACCEPT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string CANCEL_BUTTON {
            get {
                return ResourceManager.GetString("CANCEL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please check the information entered and try again..
        /// </summary>
        public static string CHECK_ENTERED_INFORMATION_LABEL {
            get {
                return ResourceManager.GetString("CHECK_ENTERED_INFORMATION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This is your 6-digit code:.
        /// </summary>
        public static string CODE_EMAIL_ADDRESS_LABEL {
            get {
                return ResourceManager.GetString("CODE_EMAIL_ADDRESS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the 6-digit code sent to your e-mail address..
        /// </summary>
        public static string CODE_INSTRUCTION_LABEL {
            get {
                return ResourceManager.GetString("CODE_INSTRUCTION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code:.
        /// </summary>
        public static string CODE_LABEL {
            get {
                return ResourceManager.GetString("CODE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm player profile.
        /// </summary>
        public static string CONFIRM_PLAYER_PROFILE_BUTTON {
            get {
                return ResourceManager.GetString("CONFIRM_PLAYER_PROFILE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to confirm the player profile?.
        /// </summary>
        public static string CONFIRM_PLAYER_PROFILE_LABEL {
            get {
                return ResourceManager.GetString("CONFIRM_PLAYER_PROFILE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm player profile..
        /// </summary>
        public static string CONFIRM_PLAYER_PROFILE_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("CONFIRM_PLAYER_PROFILE_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create match.
        /// </summary>
        public static string CREATE_MATCH_BUTTON {
            get {
                return ResourceManager.GetString("CREATE_MATCH_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create match..
        /// </summary>
        public static string CREATE_MATCH_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("CREATE_MATCH_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete player profile.
        /// </summary>
        public static string DELETE_PLAYER_PROFILE_BUTTON {
            get {
                return ResourceManager.GetString("DELETE_PLAYER_PROFILE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit player profile..
        /// </summary>
        public static string EDIT_PLAYER_PROFILE_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("EDIT_PLAYER_PROFILE_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail address:.
        /// </summary>
        public static string EMAIL_ADDRESS_LABEL {
            get {
                return ResourceManager.GetString("EMAIL_ADDRESS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No field can be left empty..
        /// </summary>
        public static string EMPTY_FIELDS_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("EMPTY_FIELDS_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter as a guest.
        /// </summary>
        public static string ENTER_AS_GUEST_BUTTON {
            get {
                return ResourceManager.GetString("ENTER_AS_GUEST_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter as a guest..
        /// </summary>
        public static string ENTER_AS_GUEST_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("ENTER_AS_GUEST_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expel player from match..
        /// </summary>
        public static string EXPEL_PLAYER_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("EXPEL_PLAYER_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Did you forget your password?.
        /// </summary>
        public static string FORGOTTEN_PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("FORGOTTEN_PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game configuration..
        /// </summary>
        public static string GAME_CONFIGURATION_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("GAME_CONFIGURATION_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information entered is invalid..
        /// </summary>
        public static string INVALID_DATA_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("INVALID_DATA_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join match.
        /// </summary>
        public static string JOIN_MATCH_BUTTON {
            get {
                return ResourceManager.GetString("JOIN_MATCH_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join match..
        /// </summary>
        public static string JOIN_MATCH_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("JOIN_MATCH_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language:.
        /// </summary>
        public static string LANGUAGE_LABEL {
            get {
                return ResourceManager.GetString("LANGUAGE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string LOGIN_BUTTON {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login..
        /// </summary>
        public static string LOGIN_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("LOGIN_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main menu..
        /// </summary>
        public static string MAIN_MENU_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("MAIN_MENU_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maternal surname:.
        /// </summary>
        public static string MATERNAL_SURNAME_LABEL {
            get {
                return ResourceManager.GetString("MATERNAL_SURNAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name:.
        /// </summary>
        public static string NAME_LABEL {
            get {
                return ResourceManager.GetString("NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No connection to the database..
        /// </summary>
        public static string NO_DATABASE_CONNECTION_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("NO_DATABASE_CONNECTION_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No connection to the server..
        /// </summary>
        public static string NO_SERVER_CONNECTION_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("NO_SERVER_CONNECTION_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password must have lowercase letters, an uppercase letter, a number and a minimum length of 8 digits..
        /// </summary>
        public static string PASSWORD_INSTRUCTION_LABEL {
            get {
                return ResourceManager.GetString("PASSWORD_INSTRUCTION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password:.
        /// </summary>
        public static string PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your e-mail address to search your player profile and send to you the password recovery code..
        /// </summary>
        public static string PASSWORD_RECOVERY_INSTRUCTION_LABEL {
            get {
                return ResourceManager.GetString("PASSWORD_RECOVERY_INSTRUCTION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover player profile password..
        /// </summary>
        public static string PASSWORD_RECOVERY_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("PASSWORD_RECOVERY_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paternal surname:.
        /// </summary>
        public static string PATERNAL_SURNAME_LABEL {
            get {
                return ResourceManager.GetString("PATERNAL_SURNAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information entered corresponds to a player profile that is already registered in the system..
        /// </summary>
        public static string PLAYER_PROFILE_ALREADY_REGISTERED_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("PLAYER_PROFILE_ALREADY_REGISTERED_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the profile picture of the player..
        /// </summary>
        public static string PROFILE_PICTURE_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("PROFILE_PICTURE_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the 6-digit code sent to your e-mail address and a new password..
        /// </summary>
        public static string REGISTER_PASSWORD_INSTRUCTION_LABEL {
            get {
                return ResourceManager.GetString("REGISTER_PASSWORD_INSTRUCTION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register player profile.
        /// </summary>
        public static string REGISTER_PLAYER_PROFILE_BUTTON {
            get {
                return ResourceManager.GetString("REGISTER_PLAYER_PROFILE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register player profile..
        /// </summary>
        public static string REGISTER_PLAYER_PROFILE_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("REGISTER_PLAYER_PROFILE_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information was correctly recorded in the system..
        /// </summary>
        public static string REGISTERED_INFORMATION_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("REGISTERED_INFORMATION_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send real time message..
        /// </summary>
        public static string SEND_REAL_TIME_MESSAGE_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("SEND_REAL_TIME_MESSAGE_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please try again later..
        /// </summary>
        public static string TRY_AGAIN_LATER_LABEL {
            get {
                return ResourceManager.GetString("TRY_AGAIN_LATER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username:.
        /// </summary>
        public static string USERNAME_LABEL {
            get {
                return ResourceManager.GetString("USERNAME_LABEL", resourceCulture);
            }
        }
    }
}
