//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parlis.Server.DataAccess
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Match
    {
        public int IdMatch { get; set; }
        public System.DateTime Date { get; set; }
        public string PlayerProfileUsername { get; set; }
    
        public virtual PlayerProfile PlayerProfile { get; set; }
    }
}
