//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parlis.Client.Services {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Parlis.Server.Service.Data")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerProfileUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerProfileUsername {
            get {
                return this.PlayerProfileUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerProfileUsernameField, value) != true)) {
                    this.PlayerProfileUsernameField = value;
                    this.RaisePropertyChanged("PlayerProfileUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Parlis.Server.Service.Data")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaternalSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaternalSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerProfileUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaternalSurname {
            get {
                return this.MaternalSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.MaternalSurnameField, value) != true)) {
                    this.MaternalSurnameField = value;
                    this.RaisePropertyChanged("MaternalSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaternalSurname {
            get {
                return this.PaternalSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.PaternalSurnameField, value) != true)) {
                    this.PaternalSurnameField = value;
                    this.RaisePropertyChanged("PaternalSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerProfileUsername {
            get {
                return this.PlayerProfileUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerProfileUsernameField, value) != true)) {
                    this.PlayerProfileUsernameField = value;
                    this.RaisePropertyChanged("PlayerProfileUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerProfile", Namespace="http://schemas.datacontract.org/2004/07/Parlis.Server.Service.Data")]
    [System.SerializableAttribute()]
    public partial class PlayerProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsVerifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVerified {
            get {
                return this.IsVerifiedField;
            }
            set {
                if ((this.IsVerifiedField.Equals(value) != true)) {
                    this.IsVerifiedField = value;
                    this.RaisePropertyChanged("IsVerified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="http://schemas.datacontract.org/2004/07/Parlis.Server.Service.Data")]
    [System.SerializableAttribute()]
    public partial class Match : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerProfileUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerProfileUsername {
            get {
                return this.PlayerProfileUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerProfileUsernameField, value) != true)) {
                    this.PlayerProfileUsernameField = value;
                    this.RaisePropertyChanged("PlayerProfileUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coin", Namespace="http://schemas.datacontract.org/2004/07/Parlis.Server.Service.Data")]
    [System.SerializableAttribute()]
    public partial class Coin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AtFinalRowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AtSlotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorTeamTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColorTeamValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FirstLeapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPlayingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWinnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumRollsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerProfileUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AtFinalRow {
            get {
                return this.AtFinalRowField;
            }
            set {
                if ((this.AtFinalRowField.Equals(value) != true)) {
                    this.AtFinalRowField = value;
                    this.RaisePropertyChanged("AtFinalRow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AtSlot {
            get {
                return this.AtSlotField;
            }
            set {
                if ((this.AtSlotField.Equals(value) != true)) {
                    this.AtSlotField = value;
                    this.RaisePropertyChanged("AtSlot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorTeamText {
            get {
                return this.ColorTeamTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorTeamTextField, value) != true)) {
                    this.ColorTeamTextField = value;
                    this.RaisePropertyChanged("ColorTeamText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ColorTeamValue {
            get {
                return this.ColorTeamValueField;
            }
            set {
                if ((this.ColorTeamValueField.Equals(value) != true)) {
                    this.ColorTeamValueField = value;
                    this.RaisePropertyChanged("ColorTeamValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FirstLeap {
            get {
                return this.FirstLeapField;
            }
            set {
                if ((this.FirstLeapField.Equals(value) != true)) {
                    this.FirstLeapField = value;
                    this.RaisePropertyChanged("FirstLeap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPlaying {
            get {
                return this.IsPlayingField;
            }
            set {
                if ((this.IsPlayingField.Equals(value) != true)) {
                    this.IsPlayingField = value;
                    this.RaisePropertyChanged("IsPlaying");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWinner {
            get {
                return this.IsWinnerField;
            }
            set {
                if ((this.IsWinnerField.Equals(value) != true)) {
                    this.IsWinnerField = value;
                    this.RaisePropertyChanged("IsWinner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumRolls {
            get {
                return this.NumRollsField;
            }
            set {
                if ((this.NumRollsField.Equals(value) != true)) {
                    this.NumRollsField = value;
                    this.RaisePropertyChanged("NumRolls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerProfileUsername {
            get {
                return this.PlayerProfileUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerProfileUsernameField, value) != true)) {
                    this.PlayerProfileUsernameField = value;
                    this.RaisePropertyChanged("PlayerProfileUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IChatManagement", CallbackContract=typeof(Parlis.Client.Services.IChatManagementCallback))]
    public interface IChatManagement {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManagement/ConnectToChat")]
        void ConnectToChat(string username, int code);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManagement/ConnectToChat")]
        System.Threading.Tasks.Task ConnectToChatAsync(string username, int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManagement/DisconnectFromChat", ReplyAction="http://tempuri.org/IChatManagement/DisconnectFromChatResponse")]
        void DisconnectFromChat(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManagement/DisconnectFromChat", ReplyAction="http://tempuri.org/IChatManagement/DisconnectFromChatResponse")]
        System.Threading.Tasks.Task DisconnectFromChatAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManagement/SendMessage")]
        void SendMessage(int code, Parlis.Client.Services.Message message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManagement/SendMessage")]
        System.Threading.Tasks.Task SendMessageAsync(int code, Parlis.Client.Services.Message message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatManagementCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManagement/ReceiveMessages", ReplyAction="http://tempuri.org/IChatManagement/ReceiveMessagesResponse")]
        void ReceiveMessages(Parlis.Client.Services.Message[] messages);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatManagementChannel : Parlis.Client.Services.IChatManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatManagementClient : System.ServiceModel.DuplexClientBase<Parlis.Client.Services.IChatManagement>, Parlis.Client.Services.IChatManagement {
        
        public ChatManagementClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatManagementClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ConnectToChat(string username, int code) {
            base.Channel.ConnectToChat(username, code);
        }
        
        public System.Threading.Tasks.Task ConnectToChatAsync(string username, int code) {
            return base.Channel.ConnectToChatAsync(username, code);
        }
        
        public void DisconnectFromChat(string username) {
            base.Channel.DisconnectFromChat(username);
        }
        
        public System.Threading.Tasks.Task DisconnectFromChatAsync(string username) {
            return base.Channel.DisconnectFromChatAsync(username);
        }
        
        public void SendMessage(int code, Parlis.Client.Services.Message message) {
            base.Channel.SendMessage(code, message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(int code, Parlis.Client.Services.Message message) {
            return base.Channel.SendMessageAsync(code, message);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IMatchManagement", CallbackContract=typeof(Parlis.Client.Services.IMatchManagementCallback))]
    public interface IMatchManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManagement/CheckMatchExistence", ReplyAction="http://tempuri.org/IMatchManagement/CheckMatchExistenceResponse")]
        bool CheckMatchExistence(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManagement/CheckMatchExistence", ReplyAction="http://tempuri.org/IMatchManagement/CheckMatchExistenceResponse")]
        System.Threading.Tasks.Task<bool> CheckMatchExistenceAsync(int code);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManagement/ConnectToMatch")]
        void ConnectToMatch(string username, int code);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManagement/ConnectToMatch")]
        System.Threading.Tasks.Task ConnectToMatchAsync(string username, int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManagement/CreateMatch", ReplyAction="http://tempuri.org/IMatchManagement/CreateMatchResponse")]
        void CreateMatch(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManagement/CreateMatch", ReplyAction="http://tempuri.org/IMatchManagement/CreateMatchResponse")]
        System.Threading.Tasks.Task CreateMatchAsync(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManagement/DisconnectFromMatch", ReplyAction="http://tempuri.org/IMatchManagement/DisconnectFromMatchResponse")]
        void DisconnectFromMatch(string username, int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManagement/DisconnectFromMatch", ReplyAction="http://tempuri.org/IMatchManagement/DisconnectFromMatchResponse")]
        System.Threading.Tasks.Task DisconnectFromMatchAsync(string username, int code);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManagement/ExpelPlayerProfile")]
        void ExpelPlayerProfile(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManagement/ExpelPlayerProfile")]
        System.Threading.Tasks.Task ExpelPlayerProfileAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManagement/GetPlayerProfiles")]
        void GetPlayerProfiles(string username, int code);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManagement/GetPlayerProfiles")]
        System.Threading.Tasks.Task GetPlayerProfilesAsync(string username, int code);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManagement/SetBoards")]
        void SetBoards();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManagement/SetBoards")]
        System.Threading.Tasks.Task SetBoardsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchManagementCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManagement/ExpelPlayerProfileFromMatch", ReplyAction="http://tempuri.org/IMatchManagement/ExpelPlayerProfileFromMatchResponse")]
        void ExpelPlayerProfileFromMatch(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManagement/ReceivePlayerProfiles", ReplyAction="http://tempuri.org/IMatchManagement/ReceivePlayerProfilesResponse")]
        void ReceivePlayerProfiles(string[] playerProfiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManagement/StartMatch", ReplyAction="http://tempuri.org/IMatchManagement/StartMatchResponse")]
        void StartMatch();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchManagementChannel : Parlis.Client.Services.IMatchManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchManagementClient : System.ServiceModel.DuplexClientBase<Parlis.Client.Services.IMatchManagement>, Parlis.Client.Services.IMatchManagement {
        
        public MatchManagementClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MatchManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MatchManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchManagementClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool CheckMatchExistence(int code) {
            return base.Channel.CheckMatchExistence(code);
        }
        
        public System.Threading.Tasks.Task<bool> CheckMatchExistenceAsync(int code) {
            return base.Channel.CheckMatchExistenceAsync(code);
        }
        
        public void ConnectToMatch(string username, int code) {
            base.Channel.ConnectToMatch(username, code);
        }
        
        public System.Threading.Tasks.Task ConnectToMatchAsync(string username, int code) {
            return base.Channel.ConnectToMatchAsync(username, code);
        }
        
        public void CreateMatch(int code) {
            base.Channel.CreateMatch(code);
        }
        
        public System.Threading.Tasks.Task CreateMatchAsync(int code) {
            return base.Channel.CreateMatchAsync(code);
        }
        
        public void DisconnectFromMatch(string username, int code) {
            base.Channel.DisconnectFromMatch(username, code);
        }
        
        public System.Threading.Tasks.Task DisconnectFromMatchAsync(string username, int code) {
            return base.Channel.DisconnectFromMatchAsync(username, code);
        }
        
        public void ExpelPlayerProfile(string username) {
            base.Channel.ExpelPlayerProfile(username);
        }
        
        public System.Threading.Tasks.Task ExpelPlayerProfileAsync(string username) {
            return base.Channel.ExpelPlayerProfileAsync(username);
        }
        
        public void GetPlayerProfiles(string username, int code) {
            base.Channel.GetPlayerProfiles(username, code);
        }
        
        public System.Threading.Tasks.Task GetPlayerProfilesAsync(string username, int code) {
            return base.Channel.GetPlayerProfilesAsync(username, code);
        }
        
        public void SetBoards() {
            base.Channel.SetBoards();
        }
        
        public System.Threading.Tasks.Task SetBoardsAsync() {
            return base.Channel.SetBoardsAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IPlayerProfileManagement")]
    public interface IPlayerProfileManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/CheckPlayerExistence", ReplyAction="http://tempuri.org/IPlayerProfileManagement/CheckPlayerExistenceResponse")]
        bool CheckPlayerExistence(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/CheckPlayerExistence", ReplyAction="http://tempuri.org/IPlayerProfileManagement/CheckPlayerExistenceResponse")]
        System.Threading.Tasks.Task<bool> CheckPlayerExistenceAsync(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/CheckPlayerProfileExistence", ReplyAction="http://tempuri.org/IPlayerProfileManagement/CheckPlayerProfileExistenceResponse")]
        bool CheckPlayerProfileExistence(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/CheckPlayerProfileExistence", ReplyAction="http://tempuri.org/IPlayerProfileManagement/CheckPlayerProfileExistenceResponse")]
        System.Threading.Tasks.Task<bool> CheckPlayerProfileExistenceAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/DeletePlayer", ReplyAction="http://tempuri.org/IPlayerProfileManagement/DeletePlayerResponse")]
        bool DeletePlayer(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/DeletePlayer", ReplyAction="http://tempuri.org/IPlayerProfileManagement/DeletePlayerResponse")]
        System.Threading.Tasks.Task<bool> DeletePlayerAsync(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/DeletePlayerProfile", ReplyAction="http://tempuri.org/IPlayerProfileManagement/DeletePlayerProfileResponse")]
        bool DeletePlayerProfile(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/DeletePlayerProfile", ReplyAction="http://tempuri.org/IPlayerProfileManagement/DeletePlayerProfileResponse")]
        System.Threading.Tasks.Task<bool> DeletePlayerProfileAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/GetPlayer", ReplyAction="http://tempuri.org/IPlayerProfileManagement/GetPlayerResponse")]
        Parlis.Client.Services.Player GetPlayer(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/GetPlayer", ReplyAction="http://tempuri.org/IPlayerProfileManagement/GetPlayerResponse")]
        System.Threading.Tasks.Task<Parlis.Client.Services.Player> GetPlayerAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/GetPlayerProfile", ReplyAction="http://tempuri.org/IPlayerProfileManagement/GetPlayerProfileResponse")]
        Parlis.Client.Services.PlayerProfile GetPlayerProfile(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/GetPlayerProfile", ReplyAction="http://tempuri.org/IPlayerProfileManagement/GetPlayerProfileResponse")]
        System.Threading.Tasks.Task<Parlis.Client.Services.PlayerProfile> GetPlayerProfileAsync(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/Login", ReplyAction="http://tempuri.org/IPlayerProfileManagement/LoginResponse")]
        Parlis.Client.Services.PlayerProfile Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/Login", ReplyAction="http://tempuri.org/IPlayerProfileManagement/LoginResponse")]
        System.Threading.Tasks.Task<Parlis.Client.Services.PlayerProfile> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/RegisterPlayer", ReplyAction="http://tempuri.org/IPlayerProfileManagement/RegisterPlayerResponse")]
        bool RegisterPlayer(Parlis.Client.Services.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/RegisterPlayer", ReplyAction="http://tempuri.org/IPlayerProfileManagement/RegisterPlayerResponse")]
        System.Threading.Tasks.Task<bool> RegisterPlayerAsync(Parlis.Client.Services.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/RegisterPlayerProfile", ReplyAction="http://tempuri.org/IPlayerProfileManagement/RegisterPlayerProfileResponse")]
        bool RegisterPlayerProfile(Parlis.Client.Services.PlayerProfile playerProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/RegisterPlayerProfile", ReplyAction="http://tempuri.org/IPlayerProfileManagement/RegisterPlayerProfileResponse")]
        System.Threading.Tasks.Task<bool> RegisterPlayerProfileAsync(Parlis.Client.Services.PlayerProfile playerProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/SendMail", ReplyAction="http://tempuri.org/IPlayerProfileManagement/SendMailResponse")]
        bool SendMail(string username, string title, string message, int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/SendMail", ReplyAction="http://tempuri.org/IPlayerProfileManagement/SendMailResponse")]
        System.Threading.Tasks.Task<bool> SendMailAsync(string username, string title, string message, int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/UpdatePlayer", ReplyAction="http://tempuri.org/IPlayerProfileManagement/UpdatePlayerResponse")]
        bool UpdatePlayer(Parlis.Client.Services.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/UpdatePlayer", ReplyAction="http://tempuri.org/IPlayerProfileManagement/UpdatePlayerResponse")]
        System.Threading.Tasks.Task<bool> UpdatePlayerAsync(Parlis.Client.Services.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/UpdatePlayerProfile", ReplyAction="http://tempuri.org/IPlayerProfileManagement/UpdatePlayerProfileResponse")]
        bool UpdatePlayerProfile(Parlis.Client.Services.PlayerProfile playerProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerProfileManagement/UpdatePlayerProfile", ReplyAction="http://tempuri.org/IPlayerProfileManagement/UpdatePlayerProfileResponse")]
        System.Threading.Tasks.Task<bool> UpdatePlayerProfileAsync(Parlis.Client.Services.PlayerProfile playerProfile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerProfileManagementChannel : Parlis.Client.Services.IPlayerProfileManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerProfileManagementClient : System.ServiceModel.ClientBase<Parlis.Client.Services.IPlayerProfileManagement>, Parlis.Client.Services.IPlayerProfileManagement {
        
        public PlayerProfileManagementClient() {
        }
        
        public PlayerProfileManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerProfileManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerProfileManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerProfileManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckPlayerExistence(string emailAddress) {
            return base.Channel.CheckPlayerExistence(emailAddress);
        }
        
        public System.Threading.Tasks.Task<bool> CheckPlayerExistenceAsync(string emailAddress) {
            return base.Channel.CheckPlayerExistenceAsync(emailAddress);
        }
        
        public bool CheckPlayerProfileExistence(string username) {
            return base.Channel.CheckPlayerProfileExistence(username);
        }
        
        public System.Threading.Tasks.Task<bool> CheckPlayerProfileExistenceAsync(string username) {
            return base.Channel.CheckPlayerProfileExistenceAsync(username);
        }
        
        public bool DeletePlayer(string emailAddress) {
            return base.Channel.DeletePlayer(emailAddress);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePlayerAsync(string emailAddress) {
            return base.Channel.DeletePlayerAsync(emailAddress);
        }
        
        public bool DeletePlayerProfile(string username) {
            return base.Channel.DeletePlayerProfile(username);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePlayerProfileAsync(string username) {
            return base.Channel.DeletePlayerProfileAsync(username);
        }
        
        public Parlis.Client.Services.Player GetPlayer(string username) {
            return base.Channel.GetPlayer(username);
        }
        
        public System.Threading.Tasks.Task<Parlis.Client.Services.Player> GetPlayerAsync(string username) {
            return base.Channel.GetPlayerAsync(username);
        }
        
        public Parlis.Client.Services.PlayerProfile GetPlayerProfile(string emailAddress) {
            return base.Channel.GetPlayerProfile(emailAddress);
        }
        
        public System.Threading.Tasks.Task<Parlis.Client.Services.PlayerProfile> GetPlayerProfileAsync(string emailAddress) {
            return base.Channel.GetPlayerProfileAsync(emailAddress);
        }
        
        public Parlis.Client.Services.PlayerProfile Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<Parlis.Client.Services.PlayerProfile> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public bool RegisterPlayer(Parlis.Client.Services.Player player) {
            return base.Channel.RegisterPlayer(player);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterPlayerAsync(Parlis.Client.Services.Player player) {
            return base.Channel.RegisterPlayerAsync(player);
        }
        
        public bool RegisterPlayerProfile(Parlis.Client.Services.PlayerProfile playerProfile) {
            return base.Channel.RegisterPlayerProfile(playerProfile);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterPlayerProfileAsync(Parlis.Client.Services.PlayerProfile playerProfile) {
            return base.Channel.RegisterPlayerProfileAsync(playerProfile);
        }
        
        public bool SendMail(string username, string title, string message, int code) {
            return base.Channel.SendMail(username, title, message, code);
        }
        
        public System.Threading.Tasks.Task<bool> SendMailAsync(string username, string title, string message, int code) {
            return base.Channel.SendMailAsync(username, title, message, code);
        }
        
        public bool UpdatePlayer(Parlis.Client.Services.Player player) {
            return base.Channel.UpdatePlayer(player);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePlayerAsync(Parlis.Client.Services.Player player) {
            return base.Channel.UpdatePlayerAsync(player);
        }
        
        public bool UpdatePlayerProfile(Parlis.Client.Services.PlayerProfile playerProfile) {
            return base.Channel.UpdatePlayerProfile(playerProfile);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePlayerProfileAsync(Parlis.Client.Services.PlayerProfile playerProfile) {
            return base.Channel.UpdatePlayerProfileAsync(playerProfile);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IGameManagement", CallbackContract=typeof(Parlis.Client.Services.IGameManagementCallback))]
    public interface IGameManagement {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/ConnectToBoard")]
        void ConnectToBoard(string username, int code);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/ConnectToBoard")]
        System.Threading.Tasks.Task ConnectToBoardAsync(string username, int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManagement/DisconnectFromBoard", ReplyAction="http://tempuri.org/IGameManagement/DisconnectFromBoardResponse")]
        void DisconnectFromBoard(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManagement/DisconnectFromBoard", ReplyAction="http://tempuri.org/IGameManagement/DisconnectFromBoardResponse")]
        System.Threading.Tasks.Task DisconnectFromBoardAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/GetCoinsByBoard")]
        void GetCoinsByBoard(string username, int code);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/GetCoinsByBoard")]
        System.Threading.Tasks.Task GetCoinsByBoardAsync(string username, int code);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/LeaveMatch")]
        void LeaveMatch(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/LeaveMatch")]
        System.Threading.Tasks.Task LeaveMatchAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/SetCoinToMove")]
        void SetCoinToMove(int turn);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/SetCoinToMove")]
        System.Threading.Tasks.Task SetCoinToMoveAsync(int turn);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/SetNextTurn")]
        void SetNextTurn();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/SetNextTurn")]
        System.Threading.Tasks.Task SetNextTurnAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/ThrowDice")]
        void ThrowDice();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManagement/ThrowDice")]
        System.Threading.Tasks.Task ThrowDiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManagement/RegisterMatch", ReplyAction="http://tempuri.org/IGameManagement/RegisterMatchResponse")]
        bool RegisterMatch(Parlis.Client.Services.Match match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManagement/RegisterMatch", ReplyAction="http://tempuri.org/IGameManagement/RegisterMatchResponse")]
        System.Threading.Tasks.Task<bool> RegisterMatchAsync(Parlis.Client.Services.Match match);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameManagementCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManagement/MoveInNormalPath", ReplyAction="http://tempuri.org/IGameManagement/MoveInNormalPathResponse")]
        void MoveInNormalPath(int turnPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManagement/ReceiveCoinsForBoard", ReplyAction="http://tempuri.org/IGameManagement/ReceiveCoinsForBoardResponse")]
        void ReceiveCoinsForBoard(Parlis.Client.Services.Coin[] coins);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManagement/ShowDiceResult", ReplyAction="http://tempuri.org/IGameManagement/ShowDiceResultResponse")]
        void ShowDiceResult(int diceResult);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManagement/ShowDisconnectedPlayerProfile", ReplyAction="http://tempuri.org/IGameManagement/ShowDisconnectedPlayerProfileResponse")]
        void ShowDisconnectedPlayerProfile(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManagement/ShowNextTurn", ReplyAction="http://tempuri.org/IGameManagement/ShowNextTurnResponse")]
        void ShowNextTurn();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameManagementChannel : Parlis.Client.Services.IGameManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameManagementClient : System.ServiceModel.DuplexClientBase<Parlis.Client.Services.IGameManagement>, Parlis.Client.Services.IGameManagement {
        
        public GameManagementClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameManagementClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameManagementClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ConnectToBoard(string username, int code) {
            base.Channel.ConnectToBoard(username, code);
        }
        
        public System.Threading.Tasks.Task ConnectToBoardAsync(string username, int code) {
            return base.Channel.ConnectToBoardAsync(username, code);
        }
        
        public void DisconnectFromBoard(string username) {
            base.Channel.DisconnectFromBoard(username);
        }
        
        public System.Threading.Tasks.Task DisconnectFromBoardAsync(string username) {
            return base.Channel.DisconnectFromBoardAsync(username);
        }
        
        public void GetCoinsByBoard(string username, int code) {
            base.Channel.GetCoinsByBoard(username, code);
        }
        
        public System.Threading.Tasks.Task GetCoinsByBoardAsync(string username, int code) {
            return base.Channel.GetCoinsByBoardAsync(username, code);
        }
        
        public void LeaveMatch(string username) {
            base.Channel.LeaveMatch(username);
        }
        
        public System.Threading.Tasks.Task LeaveMatchAsync(string username) {
            return base.Channel.LeaveMatchAsync(username);
        }
        
        public void SetCoinToMove(int turn) {
            base.Channel.SetCoinToMove(turn);
        }
        
        public System.Threading.Tasks.Task SetCoinToMoveAsync(int turn) {
            return base.Channel.SetCoinToMoveAsync(turn);
        }
        
        public void SetNextTurn() {
            base.Channel.SetNextTurn();
        }
        
        public System.Threading.Tasks.Task SetNextTurnAsync() {
            return base.Channel.SetNextTurnAsync();
        }
        
        public void ThrowDice() {
            base.Channel.ThrowDice();
        }
        
        public System.Threading.Tasks.Task ThrowDiceAsync() {
            return base.Channel.ThrowDiceAsync();
        }
        
        public bool RegisterMatch(Parlis.Client.Services.Match match) {
            return base.Channel.RegisterMatch(match);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterMatchAsync(Parlis.Client.Services.Match match) {
            return base.Channel.RegisterMatchAsync(match);
        }
    }
}
